### ISSUE TITLE
Update to new version 1.18.1

### ISSUE THREAD

**Issue by julian-alarcon** [Tyriar/vscode-snap#1]
Hi!

I wish that that you update this to the new version. I know that you are trying to transfer this to MS
https://github.com/Microsoft/vscode/issues/5458

**Comment by Tyriar** [comment]
This repo has already been merged into the vscode repo https://github.com/Microsoft/vscode/blob/master/resources/linux/snap/snapcraft.yaml

I just came back from vacation and will likely be working on this again in late Jan/early Feb.
